language: python

python:
  - 2.7

services: sqlite3

env:
  - DJANGO=1.11.7

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - export PYTHONPATH=$HOME/builds/alirizwi/django_app
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet